# Generated by Django 3.1 on 2020-09-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat_index',
            fields=[
                ('query', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
    ]
